services:
  mq-listener:
    container_name: mq-listener
    environment:
      - SERVICE_NAME=mq-listener
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    restart: always
    networks:
      - labs-net

networks:
  labs-net:
    external: true
